### ISSUE TITLE
コミットメッセージはイシュー番号だけでなく必ず作業内容を文字で書いて下さい

### ISSUE THREAD

**Issue by norotime** [yuto0331/truck#10]
コミットメッセージで何をしたのかを伝えられないと *コミュニケーション能力がない* と見なされます。
![2018-04-07 20 12 32](https://user-images.githubusercontent.com/7435505/38454324-1d835158-3aa0-11e8-9328-c3f1ce38384a.png)

理解して、次回からきちんと書くと決意したら、クローズして下さい。

**Comment by yuto0331** [comment]
イシューのクローズ時に、必ず作業内容を書くようにします。
