### ISSUE TITLE
不要な空行は削除する

### ISSUE THREAD

**Issue by norotime** [yuto0331/truck#9]
https://github.com/yuto0331/truck/blob/4aeba9bc71b45e672eb5688d1588a2ca28f5616f/app/controllers/comments_controller.rb#L19

@yuto0331 コードへの執着がないと解釈されてしまうことがあるため、よく注意しましょう。気を抜かないことです〜。
コーディング規約は暗記して下さい。
https://shugo.net/ruby-codeconv/codeconv.html

**Comment by yuto0331** [comment]
基本であろうコーディング規約を全然見れておりませんでした。
すぐ覚えるようにします。
